import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

import Header from "../components/Header";
import { useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { isLoaded, isSignedIn, user } = useUser();

  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  if (!isLoaded) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!isSignedIn ? (
            <Header />
          ) : (
            <div>
              <div>
                <Header />
                <h1>Hello {user.fullName}</h1>
              </div>
              <div>
                {data?.map((post) => (
                  <div key={post.id}>{post.content}</div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

//! STOP AT 28:43 - https://www.youtube.com/watch?v=YkOSUVzOAA4&t=1135s

export default Home;
